/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface ArtifactBytes {
  dataBase64: string
  sizeBytes: number
}

export interface CheckSessionInput {
  traceparent?: string
}

export interface CommandExecution {
  stdout: string
  stderr: string
  exitCode: number
  durationMs: number
  timedOut: boolean
  truncated: boolean
}

export interface Limits {
  outputBytesLimit: number
  fileSizeLimitBytes: number
  cpuSeconds: number
  memoryBytes: number
}

export interface ReadArtifactInput {
  traceparent?: string
  snapshots: Array<SnapshotFile>
  replayCommands: Array<ReplayCommand>
  limits: Limits
  path: string
  /**
   * the cwd a replayed entry with `cwd: None` should default to. matches
   * the sandbox's stored `defaultCwd`, so artifact extraction replays in
   * the same directory as the original commands.
   */
  defaultCwd: string
  /**
   * PYTHONPATH applied during the replay used to read the artifact. Should
   * match what was set on the original runs so imports resolve identically.
   */
  pythonpath?: string
}

export interface ReplayCommand {
  command: string
  cwd?: string
  timeoutSeconds: number
}

export interface RunSandboxInput {
  traceparent?: string
  snapshots: Array<SnapshotFile>
  replayCommands: Array<ReplayCommand>
  limits: Limits
  command: string
  cwd: string
  timeoutSeconds: number
  /**
   * PYTHONPATH applied to the materialized container. Lets skill modules
   * (`/skills/<name>`) resolve via `import` from any cwd.
   */
  pythonpath?: string
}

export interface SnapshotFile {
  skillName: string
  path: string
  encoding: string
  content: string
}
export declare function checkSession(input?: CheckSessionInput | undefined | null): Promise<void>

export declare function readArtifact(input: ReadArtifactInput): Promise<ArtifactBytes>

export declare function runSandbox(input: RunSandboxInput): Promise<CommandExecution>
